# Generated by Django 4.2.27 on 2026-01-14 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='rated_by',
            field=models.ForeignKey(limit_choices_to={'role': 'CONSUMER'}, on_delete=django.db.models.deletion.CASCADE, related_name='ratings_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rating',
            name='rated_to',
            field=models.ForeignKey(limit_choices_to={'role__in': ['MASON', 'TRADER']}, on_delete=django.db.models.deletion.CASCADE, related_name='ratings_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['rated_to'], name='ratings_rated_t_69c948_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['job'], name='ratings_job_id_e2b405_idx'),
        ),
    ]
