# Generated by Django 4.2.7 on 2026-01-30 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('PROJECT', 'Project (Construction)'), ('JOB', 'Job (Repair/Renovation)')], default='JOB', max_length=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('REPAIR', 'Repair'), ('CONSTRUCTION', 'Construction'), ('RENOVATION', 'Renovation'), ('PLUMBING', 'Plumbing'), ('ELECTRICAL', 'Electrical'), ('CARPENTRY', 'Carpentry'), ('PAINTING', 'Painting'), ('TILING', 'Tiling'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['category'], name='jobs_categor_8f96d3_idx'),
        ),
    ]
