# Generated by Django 4.2.27 on 2026-01-14 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0001_initial'),
        ('bids', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='bidder',
            field=models.ForeignKey(limit_choices_to={'role__in': ['MASON', 'TRADER']}, on_delete=django.db.models.deletion.CASCADE, related_name='bids_submitted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bid',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='jobs.job'),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['job'], name='bids_job_id_7ef571_idx'),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['bidder'], name='bids_bidder__a777a2_idx'),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['status'], name='bids_status_5924ec_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bid',
            unique_together={('job', 'bidder')},
        ),
    ]
