# Generated by Django 4.2.7 on 2026-01-30 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_category_alter_job_job_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bids', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bidder',
            field=models.ForeignKey(limit_choices_to={'role__in': ['CONTRACTOR', 'TRADER']}, on_delete=django.db.models.deletion.CASCADE, related_name='bids_submitted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='JobAcceptance',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('note', models.TextField(blank=True, help_text='Optional note from mistri')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acceptances', to='jobs.job')),
                ('mistri', models.ForeignKey(limit_choices_to={'role': 'MISTRI'}, on_delete=django.db.models.deletion.CASCADE, related_name='job_acceptances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'job_acceptances',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['job'], name='job_accepta_job_id_268966_idx'), models.Index(fields=['mistri'], name='job_accepta_mistri__505aa2_idx'), models.Index(fields=['status'], name='job_accepta_status_63f0b0_idx')],
                'unique_together': {('job', 'mistri')},
            },
        ),
    ]
