# Generated by Django 4.2.7 on 2026-01-30 15:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('min_project_value', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum project value in local currency', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('completed_projects', models.PositiveIntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'contractor_profiles',
            },
        ),
        migrations.CreateModel(
            name='MistriProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.TextField(help_text='Comma-separated skills e.g., bricklaying, plastering, tiling, carpentry')),
                ('daily_rate', models.DecimalField(decimal_places=2, help_text='Daily rate in local currency', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('available_dates', models.TextField(blank=True, help_text='JSON or comma-separated available date ranges')),
                ('completed_jobs', models.PositiveIntegerField(default=0)),
                ('sms_notifications', models.BooleanField(default=True, help_text='Receive SMS for nearby jobs')),
                ('call_notifications', models.BooleanField(default=False, help_text='Receive calls for nearby jobs')),
                ('is_verified', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mistri_profiles',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CONSUMER', 'Consumer'), ('CONTRACTOR', 'Contractor'), ('TRADER', 'Trader'), ('MISTRI', 'Mistri')], default='CONSUMER', max_length=15),
        ),
        migrations.DeleteModel(
            name='MasonProfile',
        ),
        migrations.AddField(
            model_name='mistriprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mistri_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contractorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contractor_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
